### ISSUE TITLE
Test segfaults on Mac OS X / LLVM

### ISSUE THREAD

**Issue by FreshXOpenSource** [mitghi/priqueue#1]
$ clang test.c pqueue.c -o test -I.
$ ./test
(lldb) r
Process 4528 launched: './test' (x86_64)
Process 4528 stopped
* thread #1: tid = 0xc0c0, 0x000000010000184f pqtest`insert_node + 319, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x000000010000184f pqtest`insert_node + 319
pqtest`insert_node:
->  0x10000184f <+319>: movl   (%rax), %ecx
    0x100001851 <+321>: movq   -0x10(%rbp), %rax
    0x100001855 <+325>: cmpl   (%rax), %ecx
    0x100001857 <+327>: jae    0x100001934               ; <+548>
(lldb) bt
* thread #1: tid = 0xc0c0, 0x000000010000184f pqtest`insert_node + 319, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x000000010000184f pqtest`insert_node + 319
    frame #1: 0x00000001000016f1 pqtest`priqueue_insert + 161
    frame #2: 0x000000010000146a pqtest`main + 250
    frame #3: 0x00007fffb4ada255 libdyld.dylib`start + 1
    frame #4: 0x00007fffb4ada255 libdyld.dylib`start + 1

**Comment by mitghi** [comment]
@FreshXOpenSource Thank you for reporting :) It is solved now, give it a try please.

**Comment by FreshXOpenSource** [comment]
works, thanks for your clean code and your fast response!
